[package]
name = "q_service_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.99" }
quote = "1.0"

[dev-dependencies]
q_service = { path = "../" }
thiserror = "2.0.12"
